# Generated by Django 5.2 on 2025-05-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arthub', '0005_alter_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buyer',
            new_name='user',
        ),
    ]
