# Generated by Django 5.2 on 2026-01-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arthub', '0006_rename_buyer_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='uploaded_by',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Painting', 'Painting'), ('Art Material', 'Art Material'), ('Sketch', 'Sketch'), ('Digital Art', 'Digital Art')], default='Painting', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='No description available'),
            preserve_default=False,
        ),
    ]
